### ISSUE TITLE
Add license information

### ISSUE THREAD

**Issue by vazhnov** [jasoncoon/led-mapper#1]
Hello!

I found your project from https://hackaday.com/2022/03/23/finally-a-mapping-tool-for-addressable-led-strings/

Could you please add information about the license of this repository — is it allowed to copy, change and use the code in any purpose?
It would be great to see any popular open source license.

**Comment by jasoncoon** [comment]
Done, thanks!  https://github.com/jasoncoon/led-mapper/blob/main/LICENSE

**Comment by vazhnov** [comment]
GPL v3 — great!
@jasoncoon , thank you for a lighting fast answer and solution!
