### ISSUE TITLE
Issue with Import from Sheets

### ISSUE THREAD

**Issue by yelof3** [jasoncoon/led-mapper#7]
I've used your great LED Mapper with success in the past, including [this smaller design. ](https://docs.google.com/spreadsheets/d/1toqFgaAsyjATa_0qLOe34H28APgeEiN8QNOmec49PdA/edit?usp=sharing) When copied and pasted into the mapper, with this design, both the pasted result in the layout tab and the preview in the preview controls section resemble my design. 

However, with [this big boy](https://docs.google.com/spreadsheets/d/1WFzMjSG3xfI6ik2oq1p7ODfppaKNX82Lyo7TwYq07KU/edit?usp=sharing), the output scenario is different. The preview in the layout tab (where I paste the coords) is wonky--it appears that the final digit in each of the rows is entered on the next row, as it's own row. A layout parse doesn't fix the situation. That results in a preview at the bottom that resembles my sheep, but the LEDs are off/not flowing correctly.

When writing this, I did just notice an error in LED Mapper, right under the 'Fast LED code' field in the preview controls section:  "Error: CanvasRenderingContext2D.getImageData: Argument 1 is not a finite value, so is out of range for long..". But I refreshed page and entered in coords again, and didn't see the error message the 2nd time. Maybe I accidentally entered a keystroke in the Fast LED code field, not sure what happened there...

I hope this is a clear description of my sticking point. Please let me know if I can provide any more info. Thanks!!

**Comment by jasoncoon** [comment]
OK, I see that the preview looks correct with the `physical order` pattern selected:

<img width="843" alt="image" src="https://github.com/jasoncoon/led-mapper/assets/3598755/894d636a-6f07-484e-8ae5-a89ad0355c60">

But in other patterns where the map is used, it does indeed look wonky:

<img width="843" alt="image" src="https://github.com/jasoncoon/led-mapper/assets/3598755/16dfa36c-ede5-401e-b2a3-dfa5c34a054c">

Investigating...

**Comment by yelof3** [comment]
Thanks @jasoncoon . Here's another weird thing: my issue was occurring while on my Macbook pro, on Firefox. I just got home from the studio, and pasted the Sheets data into your LED Mapper on my HP laptop, also using Firedox, and the output looks great in the input layout tab. 
![image](https://github.com/jasoncoon/led-mapper/assets/118617845/67873ac1-ef86-41c6-9b9c-4b0bf1d39d43)

However, there is an alert in the output section, and the LED rendering doesn't show. 
![image](https://github.com/jasoncoon/led-mapper/assets/118617845/e08e9464-f119-4c65-a6ee-16bf21611a96)

I opened up my Macbook Pro again just to double check the discrepancy, and sure enough, I'm getting different results between my two laptops, after pasting. Hope this helps as a lead, and doesn't add to the issue!

**Comment by jasoncoon** [comment]
OK, I just pushed a change that disables word wrapping in the layout text area. That part was just a visual problem.

It looks like your spreadsheet has a duplicate line, so I added a warning for duplicate LED indices.

But even with that fixed, the preview still isn't right. Still investigating. My guess is this is just a bug with my preview code, and that it'd look fine in actual hardware.

**Comment by jasoncoon** [comment]
OK, I just pushed another update which identifies and displays more problems with layouts.  It now finds these problems with yours:

```
Layout has 705 LEDs but only 687 unique LED indices.
Duplicate indices found: 223, 224, 225, 226, 227, 228, 229, 230, 231, 232, 233, 234, 235, 236, 237, 238, 239, 240, 241, 242.
Gaps found at indices: 68.
```

I haven't tried fixing your layout spreadsheet, so I can't say with certainty that fixing it will make it display properly in the preview, but definitely let me know if you do.

For layouts like yours, where the LEDs are sequential from left to right, top to bottom, just with empty spots, I could definitely make a "fix layout" button to automatically reindex them. It'd easily fix gaps, and could reorder the duplicates (assuming the LED count is still correct).

Some other layouts are not laid out sequentially. They might alternate direction, zig-zag, make turns, etc. Those would be harder or impossible to fix automatically.

As for your panel, does it physically match the layout spreadsheet, with empty spots?  Or is it a regular grid/matrix, with no empty spots?

**Comment by yelof3** [comment]
My original small lamb matched the layout, but for this large one, it's a regular grid/matrix. I think that I have it laid out properly for a regular grid/marix, but please let me know if not. 

Long story short---after a Sheet cleanup, everything looks good! I'm embarrassed by my erroneous sheet, and greatly appreciate you taking time out of your day to help me get to the bottom of this! I'll be in the studio maybe tomorrow, but at the latest Sunday, and will let you know if I have any issues with it manifesting on the LED panel. Thanks again!

**Comment by jasoncoon** [comment]
Glad the preview is working for you now! Behold the hypno-sheep! 🤩 

<img width="834" alt="image" src="https://github.com/jasoncoon/led-mapper/assets/3598755/d6652c86-9630-477c-bd2a-989b23abcf5e">

No problem, thanks for helping me break, troubleshoot, and make a bunch of improvements!

As for the physical layout, I don't think the generated maps will work on a regular matrix, especially if it's laid out in zig-zag order as they usually are.  Also, the map will likely not look correct if there are no physical gaps in your layout, which is what this mapper is meant to help with.  I'll need to think about how to handle that.

Garrett Mace of MaceTech has a mapper that handles this by assigning gaps to to a dummy, out of range pixel that doesn't actually exist: https://macetech.github.io/FastLED-XY-Map-Generator/

**Comment by yelof3** [comment]
You're welcome :) 
Gotcha. I wondered about that. I'm familiar with Garrett's tool, and will prep that code output from his mapper for this weekend's test. Thanks again!

**Comment by yelof3** [comment]
Might you have experience 'translating' a [FastLED XY Map Generator output](https://docs.google.com/document/d/10CQkuztxNpydhjjbGxfmGFsULHNMM2zLIWJrJ5aRGYQ/edit) into Pixelblaze? I would love to avoid writing a JSON file for this many LEDs if possible, and am hoping there's a somewhat easy way to revise the FastLED XY Map Generator code so that it fits with Pixelblaze. I'm newish to this code and have been fumbling around. Please let me know if you have any suggestions---thanks!!

**Comment by jasoncoon** [comment]
If you still have the layout or coordinates source for that map, the mapper tool already has a Pixelblaze tab in the output section:

![image](https://github.com/jasoncoon/led-mapper/assets/3598755/1ae97c79-c9d2-4d4b-b7e7-2e1b6ca594cb)

If you don't, I can definitely add a FastLED tab to the input section.

**Comment by jasoncoon** [comment]
Oh wait, sorry, that map was generated using the Macetech mapping tool?

**Comment by jasoncoon** [comment]
I converted the CSV to tab-delimited using Google Sheets: https://tinyurl.com/2k2n9bdr

The preview looks like a map of the non-masked LEDs first, then all the of the masked, blank, empty sections. So the Pixelblaze output section might work, you'd just need to update any patterns to return black for any LEDs past a certain index, I think?

![image](https://github.com/jasoncoon/led-mapper/assets/3598755/af68899c-0cee-4e93-8f6a-e91a7c963e95)

**Comment by yelof3** [comment]
Thank you Jason! I was able to edit the pattern in a way where the empty sections knocked out. It looks good in the mapper preview as seen here
<img width="1180" alt="image" src="https://github.com/jasoncoon/led-mapper/assets/118617845/917c46f6-79aa-4ead-8446-65b07d1c6d9b">
and looks good in the edit tab, as seen here. 
<img width="1237" alt="image" src="https://github.com/jasoncoon/led-mapper/assets/118617845/39c232c9-6169-46db-853c-223813d9e4e8">
But unfortunately doesn't translate to the board! I get an unrecognizable pattern. But there's progress! I'll see if I can try to figure that out, and if not will see if I can learn why on the Pixelblaze forum. If you know what might be causing that, let me know! Once again, thanks for your time!!

**Comment by jasoncoon** [comment]
I think what you've done is map a logical layout that has actual gaps to a physical layout that doesn't.
Pixelblaze doesn't, as far as I know, have any way to skip physical pixels. So you'll need to modify any patterns you want to use to send black to those pixels. I'd take this up on the ElectroMage forum, where others might be able to better help.

Or, just treat it like a regular matrix and buy black gaffer's tape over the gaps. 😆

**Comment by yelof3** [comment]
Gotcha. That makes sense. Will definitely reach out on the Pixelblaze forum if I can't figure it out on my own. Thanks a million, Jason. If you have a buymeacoffee link or whatever, send it, I'd love to send a token of my appreciation of your time here. Actually, do you provide 2 or 3 day shipping, I placed an order for one of your available discs tonight?

**Comment by jasoncoon** [comment]
No problem, and no donation or purchase is necessary, but of course if you do want something I can ship it express.
